drop table user if exists;

create table user(
    id bigint generated by default  as IDENTITY ,
    username varchar(50),
    name varchar(20),
    age int (3),
    balance decimal(10,2),
    primary key(id)
);